/* This file is automatically generated with "make include/build_env.h". DO NOT EDIT */

#ifndef _BUILD_ENV_H
#define _BUILD_ENV_H

#define BUILD_ENV_UNAME "Linux ip-172-31-11-34 4.4.0-1119-aws #133-Ubuntu SMP Tue Dec 1 19:04:22 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux"
#define BUILD_ENV_DATE "Thu Jan 28 14:32:45 UTC 2021"
#define BUILD_ENV_SRCDIR "/home/ubuntu/openwrt-sdk/build_dir/target-mipsel_24kec+dsp_uClibc-0.9.33.2/samba-3.6.25/source3"
#define BUILD_ENV_BUILDDIR "/home/ubuntu/openwrt-sdk/build_dir/target-mipsel_24kec+dsp_uClibc-0.9.33.2/samba-3.6.25/source3"
#define BUILD_ENV_USER "ubuntu"
#define BUILD_ENV_HOST "ip-172-31-11-34"
#define BUILD_ENV_COMPILER "mipsel-openwrt-linux-uclibc-gcc"
#endif /* _BUILD_ENV_H */
