#
# Copyright (C) 2020 Jo-Philipp Wich <jo@mein.io>
#
# This is free software, licensed under the Apache License, Version 2.0 .
#

include ../../build/config.mk
include ../../build/module.mk
# call BuildPackage - OpenWrt buildroot signature
